#!/bin/bash
# Checks that the commit messages conform to a specific format.

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`

while read old_sha1 new_sha1 refname; do

  git cat-file commit $new_sha1 | sed '1,/^$/d' | python $bin/check_cdh_message.py
  if [ "$?" -ne "0" ]; then exit 1; fi

done
