#!/bin/bash
# (c) Copyright 2008 Cloudera, Inc.
#
# Run the installer in unattended mode

# you must pass the path to the package's "install" program to this
installerPrgm="$1"
if [ -z "$installerPrgm" ]; then
  echo "Usage: $0 path/to/distrib/install [extra args]"
  exit 1
fi
shift

bin=`dirname $0`
bin=`cd $bin && pwd`

hadoopuser=`whoami`
if [ "$hadoopuser" == "root" ]; then
  hadoopuser="hadoop"
  sudoPrefix="sudo -H -u $hadoopuser"
else
  sudoPrefix=""
fi

# stop hadoop if it was already running.
$sudoPrefix /mnt/tmp/master/apps/hadoop-0.18.2-patched/bin/stop-all.sh
killall scribed

# remove all the directories that this will create
rm -rf /mnt/tmp/name
rm -rf /mnt/tmp/data
rm -rf /mnt/tmp/master
rm -rf /mnt/tmp/slave
rm -rf /mnt/tmp/hadoop*
rm -rf /mnt/tmp/etc/cloudera
rm -rf /tmp/cloudera
rm -rf /tmp/cloudera-installer.log

# remove extraneous trash slaves files.
rm -f /tmp/slaves-*
rm -f /tmp/distro-*.tar.gz

thishost=`hostname --fqdn`
cp ../testdata/hadoop-site.xml /tmp/install-hadoop-site.xml
sed -i -e "s/MASTER_HOST/$thishost/g" /tmp/install-hadoop-site.xml

if [ -z "$JAVA_HOME" ]; then
  # do a dir listing of /usr/java and pick the first entry.
  # this one-liner absolutizes the dirname.
  CUR_JAVA=`perl -MCwd -e 'print Cwd::abs_path(shift), "\n"' /usr/java/* | head -n 1`
else
  CUR_JAVA="$JAVA_HOME"
fi

# and launch the program
"$installerPrgm" --unattend --test-mode --prefix /mnt/tmp/master \
  --remote-prefix /mnt/tmp/slave \
  --hadoop-site /tmp/install-hadoop-site.xml \
  --hadoop-slaves ${bin}/../testdata/localhost-slaves \
  --config-prefix /mnt/tmp/etc/cloudera \
  --java-home $CUR_JAVA \
  --log-filename /tmp/cloudera-installer.log \
  --log-level DEBUG \
  --format-hdfs \
  --install-bindir \
  ../../../../bin/redist/projects/HadoopDist_supportedDistro/cloudera-hadoop-0.1.1/bin\
  --namenode "hdfs://$thishost:9000/" --jobtracker "$thishost:9001" \
  --debug \
  "$@"


