#!/usr/bin/env python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Installation tool for Cloudera Hadoop Distribution
# main entry point
#
# Usage: install [options]
# Type "install --help" for full usage instructions
#
#

import os
import sys

import com.cloudera.distribution.installproperties as installproperties
import com.cloudera.util.output as output

# use all args except program name
argv = sys.argv[1:]

# set up configuration, init stdout/stderr
properties = installproperties.InstallProperties()
output.attachOutputArgParser(properties)
output.installOutput(properties)

installproperties.loadAllProperties(properties, argv)

# if we are here, then properties and argv parsing succeeded




