#!/usr/bin/env python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Installation tool for Cloudera Hadoop Distribution
# main entry point
#
# Usage: install [options]
# Type "install --help" for full usage instructions
#
#

import os
import sys

import com.cloudera.distribution.arch as arch
import com.cloudera.distribution.installproperties as installproperties
import com.cloudera.distribution.manifest as manifest
import com.cloudera.util.output as output

# use all args except program name
argv = sys.argv[1:]

# set up configuration, init stdout/stderr
properties = installproperties.InstallProperties()
output.attachOutputArgParser(properties)
output.installOutput(properties)

installproperties.loadAllProperties(properties, argv)

# if we are here, then properties and argv parsing succeeded

# TODO: Install a log file as well

# Where are we? Switch into installer's base dir
binName = sys.argv[0]
binDir = os.path.dirname(binName)
os.chdir(binDir)

# determine what architecture / platform we're running on.
archDetector = arch.getArchDetector()
archDetector.scan()
if archDetector.getPlatform() == arch.PLATFORM_UNKNOWN:
  output.printlnInfo("Warning: Could not determine linux platform")
  output.printlnInfo("This hampers my ability to determine if you "
      + "have the correct prerequisite")
  output.printlnInfo("packages installed.")

if archDetector.getArch() == arch.ARCH_UNKNOWN:
  # TODO: Disable this warning if we don't have any 32/64-bit libs to install
  # TODO: Hadoop should give a warning if we can't lock down the arch, b/c
  #       otherwise we won't get native compression.
  output.printlnInfo("Warning: Could not determine system architecture")
  output.printlnInfo("This hampers my ability to install the correct libraries")

# Assemble installation plan from command line flags
output.printlnDebug("Creating installation plan...")
installPlan = manifest.createInstallPlan(properties)

# Detect any prereqs that we cannot install:
output.printlnInfo("Checking prerequisites for installation...")
for tool in installPlan.getInstallItems():
  tool.precheck()

output.printlnInfo("All necessary prerequisites were found.")

output.printlnInfo("""
To set up Hadoop, we need to ask you a few basic questions about your
cluster. When possible, acceptable defaults are provided to you, which you
can select by pressing [enter].
""")

for tool in installPlan.getInstallItems():
  tool.configure()

# Any user input should have occurred above this line. From this point
# forward, we only bail out because an underlying installation item
# chokes -- this is out of the user's hands by here.

# execute installation plan
for tool in installPlan.getInstallItems():
  output.printlnInfo("Installing " + tool.getName())
  tool.install()

# any steps to be performed per-tool after the whole system is together
for tool in installPlan.getInstallItems():
  output.printlnInfo("Performing postinstall for " + tool.getName())
  tool.postInstall()

# TODO: Perform automated deployment to additional machines

# Perform any verification steps that this all installed OK
for tool in installPlan.getInstallItems():
  output.printlnInfo("Verifying installation of " + tool.getName())
  tool.verify()


