#!/bin/bash
#
# (c) Copyright 2009 Cloudera, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# Starts a Hadoop secondary namenode
#
# chkconfig: 2345 90 10
# description: Hadoop secondary namenode


source /etc/rc.d/init.d/functions

source /etc/cloudera/user_env

RETVAL=0
HADOOP_USER="hadoop"
daemon="secondarynamenode"
prog="hadoop-secondarynamenode"
desc="Hadoop $daemon daemon"

start() {
  echo -n $"Starting $desc ($prog): "
  daemon --user $HADOOP_USER ${HADOOP_HOME}/bin/hadoop-daemon.sh start $daemon
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
  return $RETVAL
}

stop() {
  echo -n $"Stopping $desc ($prog): "
  daemon --user $HADOOP_USER ${HADOOP_HOME}/bin/hadoop-daemon.sh stop $daemon
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
}

restart() {
  stop
  sleep 5
  start
}

condrestart(){
  [ -e /var/lock/subsys/$prog ] && restart || :
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  condrestart|try-restart)
    condrestart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|try-restart}"
    exit 1
esac

exit $RETVAL
