#!/usr/bin/python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Test tool for Cloudera Hadoop Distribution
#

# The python sources that make up the test framework
tester = PythonTarget(
  sources=[ "src/distrotester",
            "src/remotetest",
            "src/testdistrib"],
  requiredTargets=[ "//python/Common",
                    "../installer",
                    "..:versionStamps" ],
  dataPaths = [ "profiles",
                "pig-tests",
                "hive-tests" ])


# package containing all the above python sources
pyRelease = PythonRedistTarget(
  packageName     = "distroTestPython",
  requiredTargets = [ ":tester" ])

# Jar containing Java code to run to for MapReduce tests
testsJar = JarTarget(
  jarName = "DistribTest.jar",
  sources = [ "mapreduce-tests" ],
  requiredTargets = [ "..:supportedHadoopPackage" ])


# Now we bundle all of the above together
release = PackageTarget(
  packageName = "distrotest",
  components = [
    PackageComponent(
      targetName = ":pyRelease",
      includeZip = False),
    OutputComponent(
      targetName = ":testsJar",
      destDir = "$/testjar"),

    # fast-checkpoint hadoop-site.xml configuration
    DirComponent(
      srcDir = "hadoop-configs/base",
      destDir = "$/hadoop-configs/fast-checkpoint"),
    FileComponent(
      srcFile  = "hadoop-configs/fast-checkpoint.xml",
      destFile = "$/hadoop-configs/fast-checkpoint/hadoop-site.xml"),

    # Don't want the top-level install script included in our bin dir.
    ExcludeComponent(
      name = "install"),
    ])

defaultTarget(release)

