#!/usr/bin/python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Test tool for Cloudera Hadoop Distribution
#

tester = PythonTarget(
  sources=[ "src/distrotester",
            "src/remotetest",
            "src/testdistrib"],
  requiredTargets=[ "python/Common",
                    "projects/HadoopDist/installer" ],
  dataPaths = [ "profiles" ])

