#!/usr/bin/python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Test tool for Cloudera Hadoop Distribution
#

# The python sources that make up the test framework
tester = PythonTarget(
  sources=[ "src/distrotester",
            "src/remotetest",
            "src/testdistrib"],
  required_targets=[ "//python/Common",
                    "../installer",
                    "..:versionStamps" ],
  data_paths = [ "profiles",
                "pig-tests",
                "hive-tests" ])


# package containing all the above python sources
pyRelease = PythonRedistTarget(
  package_name     = "distroTestPython",
  required_targets = [ ":tester" ])

# Jar containing Java code to run to for MapReduce tests
testsJar = JarTarget(
  jar_name = "DistribTest.jar",
  sources = [ "mapreduce-tests" ],
  required_targets = [ "..:supportedHadoopPackage" ])


# Now we bundle all of the above together
release = PackageTarget(
  package_name = "distrotest",
  steps = [
    IncludePackage(
      target_name = ":pyRelease",
      include_zip = False),
    IncludeOutput(
      target_name = ":testsJar",
      dest_dir = "$/testjar"),

    # fast-checkpoint hadoop-site.xml configuration
    CopyDir(
      src_dir = "hadoop-configs/base",
      dest_dir = "$/hadoop-configs/fast-checkpoint"),
    CopyFile(
      src_file  = "hadoop-configs/fast-checkpoint.xml",
      dest_file = "$/hadoop-configs/fast-checkpoint/hadoop-site.xml"),

    # Don't want the top-level install script included in our bin dir.
    Remove(
      name = "$/install"),
    ])

defaultTarget(release)

