#!/bin/sh
#
BRANCH=$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
BUILDDIR="build_$BRANCH"
CDH_GIT="git@git.sf.cloudera.com:cdh.git"
REPO_GIT="git@git.sf.cloudera.com:repo.git"
REPO_GIT_BRANCH="cloudera"

usage()
{
cat <<EOF
usage: $(basename $0) options

Bootstrap the build process

OPTIONS:
  -h	Show this messages
  -b	Branch of the manifest to use (default='$BRANCH')
  -o 	Path to build directory (default='$BUILDDIR')
EOF
}

while getopts "hb:o:" OPTION
do
   case $OPTION in
      h)
         usage
         exit 1
         ;;
      b)
         BRANCH=$OPTARG
         ;;
      o)
         BUILDDIR=$OPTARG
         ;;
      ?)
         usage
         exit
         ;;
   esac
done

if [ ! -d $BUILDDIR ]
then
  mkdir -p $BUILDDIR/.repo || exit 1
fi

# Sync the build directory
pushd $BUILDDIR 1>/dev/null 2>/dev/null
REPO=".repo/repo/repo"
if [ ! -f $REPO ]
then
    REPODIR=$(dirname $REPO)
    git clone $REPO_GIT $REPODIR || exit 1
    chmod a+x $REPO
    pushd $REPODIR 1>/dev/null 2>/dev/null
    git checkout -b $REPO_GIT_BRANCH origin/$REPO_GIT_BRANCH || exit 1
    popd 1>/dev/null 2>/dev/null
fi

$REPO init -u $CDH_GIT -b $BRANCH --repo-url $REPO_GIT --no-repo-verify --repo-branch $REPO_GIT_BRANCH || exit 1
$REPO sync || exit 1

popd 1>/dev/null 2>/dev/null # BUILDDIR
