CDH_VERSION=5
CDH_CUSTOMER_PATCH=0
PREV_RELEASE_TAG=cdh4.3.0-release
export IVY_MIRROR_PROP=http://azov01.sf.cloudera.com:8081/artifactory/cloudera-mirrors/

CDH_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package

# Bigtop-utils
BIGTOP_UTILS_NAME=bigtop-utils
BIGTOP_UTILS_RELNOTES_NAME=Bigtop-utils
BIGTOP_UTILS_PKG_NAME=bigtop-utils
BIGTOP_UTILS_BASE_VERSION=0.6.0
BIGTOP_UTILS_RELEASE_VERSION=0
BIGTOP_UTILS_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package
BIGTOP_UTILS_BASE_REF=cdh5-base-$(BIGTOP_UTILS_BASE_VERSION)
BIGTOP_UTILS_BUILD_REF=HEAD
BIGTOP_UTILS_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
$(eval $(call PACKAGE,bigtop-utils,BIGTOP_UTILS))

# Bigtop-jsvc
BIGTOP_JSVC_NAME=bigtop-jsvc
BIGTOP_JSVC_RELNOTES_NAME=Apache Commons Daemon (jsvc)
BIGTOP_JSVC_PKG_NAME=bigtop-jsvc
BIGTOP_JSVC_BASE_VERSION=1.0.10
#BIGTOP_JSVC_PKG_VERSION=$(BIGTOP_JSVC_BASE_VERSION)
BIGTOP_JSVC_RELEASE_VERSION=0
BIGTOP_JSVC_TARBALL_ONLY=true
BIGTOP_JSVC_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package
BIGTOP_JSVC_BASE_REF=cdh5-base-$(BIGTOP_UTILS_BASE_VERSION)
BIGTOP_JSVC_TARBALL_SRC=commons-daemon-$(BIGTOP_JSVC_BASE_VERSION)-native-src.tar.gz
BIGTOP_JSVC_TARBALL_DST=commons-daemon-$(BIGTOP_JSVC_BASE_VERSION).tar.gz
BIGTOP_JSVC_SITE=$(CLOUDERA_ARCHIVE)
BIGTOP_JSVC_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
$(eval $(call PACKAGE,bigtop-jsvc,BIGTOP_JSVC))

# Bigtop-tomcat
BIGTOP_TOMCAT_NAME=bigtop-tomcat
BIGTOP_TOMCAT_RELNOTES_NAME=Apache Tomcat
BIGTOP_TOMCAT_PKG_NAME=bigtop-tomcat
BIGTOP_TOMCAT_BASE_VERSION=6.0.37
#BIGTOP_TOMCAT_PKG_VERSION=$(BIGTOP_TOMCAT_BASE_VERSION)
BIGTOP_TOMCAT_RELEASE_VERSION=0
BIGTOP_TOMCAT_TARBALL_ONLY=true
BIGTOP_TOMCAT_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package
BIGTOP_TOMCAT_BASE_REF=cdh5-base-$(BIGTOP_UTILS_BASE_VERSION)
BIGTOP_TOMCAT_TARBALL_SRC=apache-tomcat-$(BIGTOP_TOMCAT_BASE_VERSION)-src.tar.gz
BIGTOP_TOMCAT_TARBALL_DST=apache-tomcat-$(BIGTOP_TOMCAT_BASE_VERSION).tar.gz
BIGTOP_TOMCAT_SITE=$(CLOUDERA_ARCHIVE)
BIGTOP_TOMCAT_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
$(eval $(call PACKAGE,bigtop-tomcat,BIGTOP_TOMCAT))

# Hadoop
HADOOP_NAME=hadoop
HADOOP_RELNOTES_NAME=Apache Hadoop
HADOOP_PKG_NAME=hadoop
HADOOP_BASE_VERSION=2.2.0
HADOOP_RELEASE_VERSION=0
HADOOP_TARBALL_DST=hadoop-2.2.0-pre-src.tar.gz
HADOOP_TARBALL_SRC=$(HADOOP_TARBALL_DST)
HADOOP_SITE=$(CLOUDERA_ARCHIVE)
HADOOP_GIT_REPO=$(REPO_DIR)/cdh5/hadoop
HADOOP_BASE_REF=cdh5-base-$(HADOOP_BASE_VERSION)
HADOOP_BUILD_REF=HEAD
HADOOP_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
$(eval $(call PACKAGE,hadoop,HADOOP))

# ZooKeeper
ZOOKEEPER_NAME=zookeeper
ZOOKEEPER_RELNOTES_NAME=Apache Zookeeper
ZOOKEEPER_PKG_NAME=zookeeper
ZOOKEEPER_BASE_VERSION=3.4.5
ZOOKEEPER_RELEASE_VERSION=0
ZOOKEEPER_TARBALL_DST=zookeeper-$(ZOOKEEPER_BASE_VERSION).tar.gz
ZOOKEEPER_TARBALL_SRC=$(ZOOKEEPER_TARBALL_DST)
ZOOKEEPER_GIT_REPO=$(REPO_DIR)/cdh5/zookeeper
ZOOKEEPER_BASE_REF=cdh5-base-$(ZOOKEEPER_BASE_VERSION)
ZOOKEEPER_BUILD_REF=cdh5-$(ZOOKEEPER_BASE_VERSION)
ZOOKEEPER_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
ZOOKEEPER_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,zookeeper,ZOOKEEPER))

# HBase
HBASE_NAME=hbase
HBASE_RELNOTES_NAME=Apache HBase
HBASE_PKG_NAME=hbase
HBASE_BASE_VERSION=0.95.2
HBASE_RELEASE_VERSION=0
HBASE_TARBALL_DST=hbase-$(HBASE_BASE_VERSION)-src.tar.gz
HBASE_TARBALL_SRC=$(HBASE_TARBALL_DST)
HBASE_GIT_REPO=$(REPO_DIR)/cdh5/hbase
HBASE_BASE_REF=cdh5-base-$(HBASE_BASE_VERSION)
HBASE_BUILD_REF=cdh5-$(HBASE_BASE_VERSION)
HBASE_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
HBASE_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,hbase,HBASE))

# Pig
PIG_NAME=pig
PIG_RELNOTES_NAME=Apache Pig
PIG_PKG_NAME=pig
PIG_BASE_VERSION=0.12.0
PIG_RELEASE_VERSION=0
PIG_TARBALL_DST=pig-$(PIG_BASE_VERSION).tar.gz
PIG_TARBALL_SRC=$(PIG_TARBALL_DST)
PIG_GIT_REPO=$(REPO_DIR)/cdh5/pig
PIG_BASE_REF=cdh5-base-$(PIG_BASE_VERSION)
PIG_BUILD_REF=cdh5-$(PIG_BASE_VERSION)
PIG_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
PIG_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,pig,PIG))

# Hive
HIVE_NAME=hive
HIVE_RELNOTES_NAME=Apache Hive
HIVE_PKG_NAME=hive
HIVE_BASE_VERSION=0.11.0
HIVE_RELEASE_VERSION=0
HIVE_TARBALL_DST=hive-$(HIVE_BASE_VERSION).tar.gz
HIVE_TARBALL_SRC=$(HIVE_TARBALL_DST)
HIVE_GIT_REPO=$(REPO_DIR)/cdh5/hive
HIVE_BASE_REF=cdh5-base-$(HIVE_BASE_VERSION)
HIVE_BUILD_REF=cdh5-$(HIVE_BASE_VERSION)
HIVE_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
HIVE_SITE=$(CLOUDERA_ARCHIVE)
HIVE_SRC_PREFIX=src/
$(eval $(call PACKAGE,hive,HIVE))

# # Sqoop
SQOOP_NAME=sqoop
SQOOP_RELNOTES_NAME=Sqoop
SQOOP_PKG_NAME=sqoop
SQOOP_BASE_VERSION=1.4.4
SQOOP_RELEASE_VERSION=0
SQOOP_TARBALL_DST=sqoop-$(SQOOP_BASE_VERSION).tar.gz
SQOOP_TARBALL_SRC=$(SQOOP_TARBALL_DST)
SQOOP_GIT_REPO=$(REPO_DIR)/cdh5/sqoop
SQOOP_BASE_REF=cdh5-base-$(SQOOP_BASE_VERSION)
SQOOP_BUILD_REF=cdh5-$(SQOOP_BASE_VERSION)
SQOOP_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
SQOOP_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,sqoop,SQOOP))

# # Sqoop 2
SQOOP2_NAME=sqoop2
SQOOP2_RELNOTES_NAME=Sqoop 2
SQOOP2_PKG_NAME=sqoop2
SQOOP2_BASE_VERSION=1.99.2
SQOOP2_RELEASE_VERSION=0
SQOOP2_TARBALL_DST=sqoop2-$(SQOOP2_BASE_VERSION).tar.gz
SQOOP2_TARBALL_SRC=sqoop-$(SQOOP2_BASE_VERSION).tar.gz
SQOOP2_GIT_REPO=$(REPO_DIR)/cdh5/sqoop2
SQOOP2_BASE_REF=cdh5-base-$(SQOOP2_BASE_VERSION)
SQOOP2_BUILD_REF=cdh5-$(SQOOP2_BASE_VERSION)
SQOOP2_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
SQOOP2_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,sqoop2,SQOOP2))

# Oozie
OOZIE_NAME=oozie
OOZIE_RELNOTES_NAME=Apache Oozie
OOZIE_PKG_NAME=oozie
OOZIE_BASE_VERSION=4.0.0
OOZIE_RELEASE_VERSION=0
OOZIE_TARBALL_DST=oozie-$(OOZIE_BASE_VERSION).tar.gz
OOZIE_TARBALL_SRC=oozie-$(OOZIE_BASE_VERSION).tar.gz
OOZIE_GIT_REPO=$(REPO_DIR)/cdh5/oozie
OOZIE_BASE_REF=cdh5-base-$(OOZIE_BASE_VERSION)
OOZIE_BUILD_REF=cdh5-$(OOZIE_BASE_VERSION)
OOZIE_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
OOZIE_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,oozie,OOZIE))

# Whirr
WHIRR_NAME=whirr
WHIRR_RELNOTES_NAME=Apache Whirr
WHIRR_PKG_NAME=whirr
WHIRR_BASE_VERSION=0.8.2
WHIRR_RELEASE_VERSION=0
WHIRR_TARBALL_DST=whirr-$(WHIRR_BASE_VERSION)-src.tar.gz
WHIRR_TARBALL_SRC=$(WHIRR_TARBALL_DST)
WHIRR_GIT_REPO=$(REPO_DIR)/cdh5/whirr
WHIRR_BASE_REF=cdh5-base-$(WHIRR_BASE_VERSION)
WHIRR_BUILD_REF=cdh5-$(WHIRR_BASE_VERSION)
WHIRR_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
WHIRR_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,whirr,WHIRR))

# $(WHIRR_TARGET_PREP):
# 	mkdir -p $($(PKG)_SOURCE_DIR)
# 	$(BASE_DIR)/tools/setup-package-build \
# 	  $($(PKG)_GIT_REPO) \
# 	  $($(PKG)_BASE_REF) \
# 	  $($(PKG)_BUILD_REF) \
# 	  $($(PKG)_DOWNLOAD_DST) \
# 	  $($(PKG)_SOURCE_DIR) \
# 	  $($(PKG)_FULL_VERSION)
# 	cp $(WHIRR_GIT_REPO)/cloudera/base.gitignore $(WHIRR_SOURCE_DIR)/.gitignore
# 	touch $@

# Flume NG
FLUME_NG_NAME=flume-ng
FLUME_NG_RELNOTES_NAME=Flume NG
FLUME_NG_PKG_NAME=flume-ng
FLUME_NG_BASE_VERSION=1.4.0
FLUME_NG_RELEASE_VERSION=0
FLUME_NG_GIT_REPO=$(REPO_DIR)/cdh5/flume-ng
FLUME_NG_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
FLUME_NG_BASE_REF=cdh5-base-$(FLUME_NG_BASE_VERSION)
FLUME_NG_BUILD_REF=cdh5-$(FLUME_NG_BASE_VERSION)
FLUME_NG_TARBALL_DST=$(FLUME_NG_NAME)-$(FLUME_NG_BASE_VERSION).tar.gz
FLUME_NG_TARBALL_SRC=apache-flume-$(FLUME_NG_BASE_VERSION)-src.tar.gz
FLUME_NG_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,flume-ng,FLUME_NG))

# Mahout
MAHOUT_NAME=mahout
MAHOUT_RELNOTES_NAME=Mahout
MAHOUT_PKG_NAME=mahout
MAHOUT_BASE_VERSION=0.8
MAHOUT_RELEASE_VERSION=0
MAHOUT_TARBALL_DST=mahout-distribution-$(MAHOUT_BASE_VERSION)-src.tar.gz
MAHOUT_TARBALL_SRC=$(MAHOUT_TARBALL_DST)
MAHOUT_GIT_REPO=$(REPO_DIR)/cdh5/mahout
MAHOUT_BASE_REF=cdh5-base-$(MAHOUT_BASE_VERSION)
MAHOUT_BUILD_REF=cdh5-$(MAHOUT_BASE_VERSION)
MAHOUT_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
MAHOUT_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,mahout,MAHOUT))

# Hue
HUE_NAME=hue
HUE_RELNOTES_NAME=$(HUE_NAME)
HUE_PKG_NAME=$(HUE_NAME)
HUE_BASE_VERSION=3.0.0
HUE_RELEASE_VERSION=0
HUE_TARBALL_DST=$(HUE_NAME)-$(HUE_BASE_VERSION)-src.tar.gz
HUE_TARBALL_SRC=$(HUE_TARBALL_DST)
HUE_GIT_REPO=$(REPO_DIR)/cdh5/hue
HUE_BASE_REF=cdh5-base-$(HUE_BASE_VERSION)
HUE_BUILD_REF=cdh5-$(HUE_BASE_VERSION)
HUE_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
HUE_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,hue,HUE))

# CDH parcel packages
CDH_PARCEL_NAME=cdh-parcel
CDH_PARCEL_RELNOTES_NAME=CDH-Parcel
CDH_PARCEL_BASE_VERSION=5.0.0
CDH_PARCEL_PKG_NAME=cdh-parcel-$(CDH_PARCEL_BASE_VERSION)
CDH_PARCEL_RELEASE_VERSION=0
CDH_PARCEL_TARBALL_DST=$(CDH_PARCEL_NAME)-$(CDH_PARCEL_BASE_VERSION).tar.gz
CDH_PARCEL_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-repos/apt
CDH_PARCEL_BASE_REF=cdh5-base-0.6.0
CDH_PARCEL_BUILD_REF=HEAD
CDH_PARCEL_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
$(eval $(call PACKAGE,cdh-parcel,CDH_PARCEL))
CDH_PARCEL_PKG_VERSION=$(CDH_PARCEL_BASE_VERSION)

# DataFu 
DATAFU_NAME=datafu
DATAFU_RELNOTES_NAME=Collection of user-defined functions
DATAFU_PKG_NAME=pig-udf-datafu
DATAFU_BASE_VERSION=1.0.0
DATAFU_RELEASE_VERSION=0
DATAFU_TARBALL_DST=datafu-$(DATAFU_BASE_VERSION).tar.gz
DATAFU_TARBALL_SRC=$(DATAFU_TARBALL_DST)
DATAFU_GIT_REPO=$(REPO_DIR)/cdh5/datafu
DATAFU_BASE_REF=cdh5-base-$(DATAFU_BASE_VERSION)
DATAFU_BUILD_REF=cdh5-$(DATAFU_BASE_VERSION)
DATAFU_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
DATAFU_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,datafu,DATAFU))

# Solr
SOLR_NAME=solr
SOLR_RELNOTES_NAME=Search engine server
SOLR_PKG_NAME=solr
SOLR_BASE_VERSION=4.4.0
SOLR_RELEASE_VERSION=0
SOLR_TARBALL_DST=solr-$(SOLR_BASE_VERSION)-src.tgz
SOLR_TARBALL_SRC=$(SOLR_TARBALL_DST)
SOLR_GIT_REPO=$(REPO_DIR)/cdh5/solr
SOLR_BASE_REF=cdh5-base-$(SOLR_BASE_VERSION)
SOLR_BUILD_REF=cdh5-$(SOLR_BASE_VERSION)
SOLR_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
SOLR_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,solr,SOLR))

# Search project 
SEARCH_NAME=search
SEARCH_RELNOTES_NAME=Cloudera Search Project
SEARCH_PKG_NAME=search
SEARCH_BASE_VERSION=1.0.0
#SEARCH_PKG_VERSION=$(SEARCH_BASE_VERSION)
SEARCH_RELEASE_VERSION=0
SEARCH_TARBALL_DST=search-$(SEARCH_BASE_VERSION).tar.gz
SEARCH_GIT_REPO=$(REPO_DIR)/cdh5/search
SEARCH_BASE_REF=cdh5-$(SEARCH_BASE_VERSION)
SEARCH_BUILD_REF=cdh5-$(SEARCH_BASE_VERSION)
SEARCH_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
SEARCH_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,search,SEARCH))

# Search project hbase-solr-indexer
HBASE_SOLR_NAME=hbase-solr
HBASE_SOLR_RELNOTES_NAME=NGData HBase indexer Project
HBASE_SOLR_PKG_NAME=hbase-solr
HBASE_SOLR_BASE_VERSION=1.3
#HBASE_SOLR_PKG_VERSION=$(HBASE_SOLR_BASE_VERSION)
HBASE_SOLR_RELEASE_VERSION=0
HBASE_SOLR_TARBALL_DST=hbase-solr-$(HBASE_SOLR_BASE_VERSION).tar.gz
HBASE_SOLR_GIT_REPO=$(REPO_DIR)/cdh5/hbase-solr
HBASE_SOLR_BASE_REF=cdh5-$(HBASE_SOLR_BASE_VERSION)
HBASE_SOLR_BUILD_REF=cdh5-$(HBASE_SOLR_BASE_VERSION)
HBASE_SOLR_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
HBASE_SOLR_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,hbase-solr,HBASE_SOLR))

# CDK
CDK_NAME=cdk
CDK_RELNOTES_NAME=Cloudera Development Kit
CDK_PKG_NAME=cdk
CDK_BASE_VERSION=0.8.0
CDK_RELEASE_VERSION=0
CDK_TARBALL_DST=cdk-$(CDK_BASE_VERSION).tar.gz
CDK_TARBALL_SRC=$(CDK_TARBALL_DST)
CDK_GIT_REPO=$(REPO_DIR)/cdh5/cdk
CDK_BASE_REF=cdh5-base-$(CDK_BASE_VERSION)
CDK_BUILD_REF=cdh5-$(CDK_BASE_VERSION)
CDK_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
CDK_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,cdk,CDK))

# Sentry 
SENTRY_NAME=sentry
SENTRY_RELNOTES_NAME=Cloudera authorization component
SENTRY_PKG_NAME=sentry
SENTRY_BASE_VERSION=1.2.0
SENTRY_RELEASE_VERSION=0
SENTRY_TARBALL_DST=sentry-$(SENTRY_BASE_VERSION).tar.gz
SENTRY_TARBALL_SRC=sentry-$(SENTRY_BASE_VERSION)-incubating.tar.gz
SENTRY_GIT_REPO=$(REPO_DIR)/cdh5/sentry
SENTRY_BASE_REF=cdh5-base-$(SENTRY_BASE_VERSION)
SENTRY_BUILD_REF=cdh5-$(SENTRY_BASE_VERSION)
SENTRY_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
SENTRY_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,sentry,SENTRY))

# Impala
IMPALA_NAME=impala
IMPALA_RELNOTES_NAME=Cloudera Impala
IMPALA_PKG_NAME=impala
IMPALA_BASE_VERSION=1.2.0
#IMPALA_PKG_VERSION=$(IMPALA_BASE_VERSION)
IMPALA_RELEASE_VERSION=0
IMPALA_BUILD_REF=cdh5-$(IMPALA_BASE_VERSION)
IMPALA_GIT_REPO=$(REPO_DIR)/cdh5/impala
IMPALA_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src/
IMPALA_TARBALL_DST=impala-$(IMPALA_BUILD_REF).tar.gz
$(eval $(call PACKAGE,impala,IMPALA))

# Llama
LLAMA_NAME=llama
LLAMA_RELNOTES_NAME=Cloudera Llama
LLAMA_PKG_NAME=llama
LLAMA_BASE_VERSION=1.0.0
#LLAMA_PKG_VERSION=$(LLAMA_BASE_VERSION)
LLAMA_RELEASE_VERSION=0
LLAMA_BUILD_REF=cdh5-1.0.0
LLAMA_GIT_REPO=$(REPO_DIR)/cdh5/llama
LLAMA_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src/
LLAMA_TARBALL_DST=llama-$(LLAMA_BUILD_REF).tar.gz
$(eval $(call PACKAGE,llama,LLAMA))

# Avro
AVRO_NAME=avro
AVRO_RELNOTES_NAME=Avro
AVRO_PKG_NAME=avro-libs
AVRO_BASE_VERSION=1.7.4
#AVRO_PKG_VERSION=$(AVRO_BASE_VERSION)
AVRO_RELEASE_VERSION=0
AVRO_BUILD_REF=cdh5-$(AVRO_BASE_VERSION)
AVRO_BASE_REF=cdh5-base-$(AVRO_BASE_VERSION)
AVRO_GIT_REPO=$(REPO_DIR)/cdh5/avro
AVRO_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
AVRO_TARBALL_DST=avro-$(AVRO_BASE_VERSION).tar.gz
AVRO_TARBALL_SRC=avro-src-$(AVRO_BASE_VERSION).tar.gz
AVRO_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,avro,AVRO))

# Parquet
PARQUET_NAME=parquet
PARQUET_RELNOTES_NAME=Columnar storage format for Hadoop
PARQUET_PKG_NAME=parquet
PARQUET_BASE_VERSION=1.0.0
#PARQUET_PKG_VERSION=$(PARQUET_BASE_VERSION)
PARQUET_RELEASE_VERSION=0
PARQUET_TARBALL_DST=parquet-$(PARQUET_BASE_VERSION).tar.gz
PARQUET_TARBALL_SRC=parquet-mr-parquet-$(PARQUET_BASE_VERSION).tar.gz
PARQUET_GIT_REPO=$(REPO_DIR)/cdh5/parquet
PARQUET_BASE_REF=cdh5-base-1.0.0
PARQUET_BUILD_REF=cdh5-$(PARQUET_BASE_VERSION)
PARQUET_PACKAGE_GIT_REPO=$(REPO_DIR)/cdh5/cdh-package/bigtop-packages/src
PARQUET_SITE=$(CLOUDERA_ARCHIVE)
$(eval $(call PACKAGE,parquet,PARQUET))

