#!/usr/bin/python
#
# (c) Copyright 2009 Cloudera, Inc.
#
# Master Targets file for Cloudera Hadoop distribution (CH) system

# Set some version constants which appear throughout this project.

# Version of Hadoop our system is based on:
base_hadoop_ver = "0.18.3"
hadoop_ver_string = "hadoop-" + base_hadoop_ver

# Cloudera Hadoop dist version.
base_ch_ver = "0.3.0"

# RPM release number
rpm_release="8.cloudera.CH0_3"

RegisterProperty('projects.HadoopDist.base_ch_ver', base_ch_ver)
RegisterProperty('projects.HadoopDist.release', rpm_release)
RegisterProperty('projects.HadoopDist.base_hadoop_ver', base_hadoop_ver)

hadoop_cloudera_ver_string = "hadoop-%s-%s" % (base_hadoop_ver, rpm_release)

version = VerStringTarget(
  version      = base_ch_ver,
  python_module = "installer.version")

# NOTE(aaron): This is not currently enabled in any way in our distribution.
# include the portal source code
# portalStep = CopyDir(
#  src_dir  = "portal/src",
#  dest_dir = "$/src/webapps/portal")



supportedHadoopPackage = PackageTarget(
  package_name = hadoop_cloudera_ver_string,
  clean_first=True,
  steps = [
    # unpack pristine hadoop
    Exec(
      executable="tar",
      arguments=["--strip-components=1",
                 "-xzf",
                 "%%(srcdir)/pristine/%s.tar.gz" % hadoop_ver_string],
      inputs=["%%(srcdir)/pristine/%s.tar.gz" % hadoop_ver_string]),
    # copy cloudera dir inside
    CopyDir(
      src_dir="hadoop",
      dest_dir="$/cloudera"),
    Exec(
      executable="%(assemblydir)/cloudera/clouderify_hadoop.py",
      arguments=["%(assemblydir)/",
                 base_hadoop_ver,
                 rpm_release
                 ]),
    AntCall(
      build_file = "$/cloudera/build.xml",
      properties = {'version': '%s-%s' % (base_hadoop_ver, rpm_release),
                    'libhdfs': 'true',
                    'compile.c++': 'true'},
      ant_target = "package"),
    Tar(
      filename= hadoop_cloudera_ver_string + ".tar.gz",
      subdir="build/%s" % (hadoop_cloudera_ver_string)
      ),
  ],
  # Define build-phase outputs that other programs compiled against our distro need.
  outputs = ["$/build/" + hadoop_cloudera_ver_string + "/" + path for path in
             [hadoop_cloudera_ver_string + "-core.jar",
              hadoop_cloudera_ver_string + "-test.jar",
              hadoop_cloudera_ver_string + "-tools.jar",
              "/build/" + hadoop_cloudera_ver_string + "-examples.jar",
              "/lib/commons-cli-2.0-SNAPSHOT.jar",
              "/lib/commons-codec-1.3.jar",
              "/lib/commons-httpclient-3.0.1.jar",
              "/lib/commons-logging-1.0.4.jar",
              "/lib/commons-logging-api-1.0.4.jar",
              "/lib/commons-net-1.4.1.jar",
              "/lib/jets3t-0.6.0.jar",
              "/lib/jetty-5.1.4.jar",
              "/lib/junit-3.8.1.jar",
              "/lib/kfs-0.1.3.jar",
              "/lib/log4j-1.2.15.jar",
              "/lib/oro-2.0.8.jar",
              "/lib/servlet-api.jar",
              "/lib/slf4j-api-1.4.3.jar",
              "/lib/slf4j-log4j12-1.4.3.jar",
              "/lib/xmlenc-0.52.jar",
              ]])

# steps for packaging

# the installation system
# NOTE(aaron): This is disabled for now
#installerStep = IncludePackage(
#  target_name = "installer:release",
#  include_zip = False, # we need this unpackacked
#  dest_dir    = "$/bin")

# the log mover system
# NOTE(aaron): This is disabled for now
#logMoverStep = IncludePackage(
#  target_name = "log_mover:release",
#  include_zip = False, # we need this unpackacked
#  dest_dir    = "$/bin/logmover")


# NOTE(aaron): Contents of doc and deps directories are not currently used/built


# Version stamps: make a single indirection point where all the
# version stamps are listed, so that the installer and test programs
# can depend on only a single place. We only need to update the current
# package version numbers in this single Targets file.
versionStamps = EmptyTarget(
  required_targets = [
    "//thirdparty/hive-chd-0.3.0:version",
    "//thirdparty/pig-0.1.1:version",
    ":version" ])

# subdirectory targets:
#   installer -- guided and noattend python installation system
#   test      -- Cluster Test tool (not included in distro itself)
ProjectList(required_targets=[
  "installer",
  "log_mover",
  "test",
  "rpm",
  "deb"
  ])
