#!/usr/bin/python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Master Targets file for Cloudera Hadoop distribution (CH) system


# List of all distribution editions we compile from this tree.
# This is the default target.
allDistributions = EmptyPackageTarget(
  requiredTargets = [ ":supportedDistro" ])


# Compile a Hadoop redist tarball to put in the distribution
supportedHadoopPackage = HadoopPackageTarget(
  packageName   = "distrib-hadoop",
  baseHadoopDir = "thirdparty/hadoop-0.18.2",
  baseVersion   = "0.18.2",
  patchPlan     = [])

# Compile a pig redist tarball to put in the distribution
pigJarComponent = OutputComponent(
  targetName = "thirdparty/pig-0.1.1")

supportedPigPackage = PackageTarget(
  packageName = "pig",
  version     = "0.1.1",
  components = [ pigJarComponent ])

# components for packaging

# Hadoop itself!
hadoopComponent = PackageComponent(
  targetName = ":supportedHadoopPackage",
  includeZip = True,
  destDir    = "packages")

# the installation system
installerComponent = PackageComponent(
  targetName = "projects/HadoopDist/installer:release",
  includeZip = False, # we need this unpackacked
  destDir    = "bin")

# take the pig tgz package we assembled above and include that
# in our distribution package.
pigPackageComponent = PackageComponent(
  targetName = ":supportedPigPackage",
  includeZip = True,
  destDir    = "packages")

# TODO: documentation component, any other scripts, pig, hive, scribe, etc

# There may be several versions of how we package the distribution.
# supportedDistro is the one released to support clients
supportedDistro = PackageTarget(
  packageName = "cloudera-hadoop",
  version     = "0.1.0",
  components  = [
    hadoopComponent,
    installerComponent,
    pigPackageComponent])


# subdirectory targets:
#   installer -- guided and noattend python installation system
ProjectList(requiredTargets=[
  "projects/HadoopDist/installer"
    ])



defaultTarget(allDistributions)

