#!/usr/bin/python
#
# (c) Copyright 2009 Cloudera, Inc.
#
# Master Targets file for Cloudera Hadoop distribution (CH) system

# Set some version constants which appear throughout this project.

# Hadoop
base_hadoop_ver = "0.20.0"

hadoop_ver_string = "hadoop-" + base_hadoop_ver
RegisterProperty('hadoop-0.20.repo', '%(srcdir)/repos/hadoop')
BacktickProperty('hadoop-0.20.version',
                 executable='//tools/branch-tool',
                 arguments=['version'],
                 dir='${hadoop-0.20.repo}')
RegisterProperty('hadoop-0.20.base.version', base_hadoop_ver)
RegisterProperty('hadoop-0.20.base.ref', 'apache/tags/release-%s' % base_hadoop_ver)
RegisterProperty('hadoop-0.20.build.ref', 'cdh-0.20.0')
RegisterProperty('hadoop-0.20.pristine.tarball',
                 '%%(srcdir)/repos/pristine/%s.tar.gz' % hadoop_ver_string)


# Pig
base_pig_ver="0.2.0"
pig_ver_string="pig-" + base_pig_ver

RegisterProperty('pig.base.version', base_pig_ver)
RegisterProperty('pig.repo', '%(srcdir)/repos/pig')
RegisterProperty('pig.base.ref', 'apache/tags/release-%s' % base_pig_ver)
RegisterProperty('pig.build.ref', 'cdh-0.18')
RegisterProperty('pig.pristine.tarball',
                 '%%(srcdir)/repos/pristine/%s.tar.gz' % pig_ver_string)


# Hive
base_hive_ver="0.3.0"
hive_ver_string="hive-" + base_hive_ver

RegisterProperty('hive.base.version', base_hive_ver)
RegisterProperty('hive.repo', '%(srcdir)/repos/hive')
RegisterProperty('hive.base.ref', 'apache/tags/release-%s' % base_hive_ver)
RegisterProperty('hive.build.ref', 'cdh-0.18')
RegisterProperty('hive.pristine.tarball',
                 '%(srcdir)/repos/pristine/hive-0.3.0-hadoop-0.18.0-dev.tar.gz')

supportedHadoopPackage = PackageTarget(
  package_name = "hadoop-build",
  clean_first=True,
  create_tarball=False,
  steps = [
    cloudera.SetupBuildStep("hadoop-0.20"),
  # Apply patches
    Exec(
      executable="%(assemblydir)/cloudera/apply-patches",
      arguments=["%(assemblydir)/",
                 "%(assemblydir)/cloudera/patches"]),
    Exec(
      executable="%(assemblydir)/cloudera/do-release-build",
      env={
       'JAVA32_HOME': '${java32.home}',
       'JAVA64_HOME': '${java64.home}',
       'JAVA5_HOME':  '${java5-home}',
       'FORREST_HOME': '${forrest-home}',
      }),
  ],
  outputs=[
    '%(assemblydir)/build/hadoop-${hadoop-0.20.version}.tar.gz',
    ]      
  )

# subdirectory targets:
ProjectList(required_targets=[
  "repos/hadoop-package/:rpm",
  "repos/hadoop-package/:deb",
  "repos/hive-package/:rpm",
  "repos/hive-package/:deb",
  "repos/pig-package/:rpm",
  "repos/pig-package/:deb",
  ":supportedHadoopPackage",
  ])
