#!/usr/bin/python
#
# (c) Copyright 2009 Cloudera, Inc.
#
# Master Targets file for Cloudera Hadoop distribution (CH) system

# Set some version constants which appear throughout this project.

# Version of Hadoop our system is based on:
base_hadoop_ver = "0.18.3"
hadoop_ver_string = "hadoop-" + base_hadoop_ver

# Cloudera Hadoop dist version.
base_ch_ver = "0.3.0"

# RPM release number
rpm_release="7.cloudera.CH0_3"

# This is the default target.
# This is the distribution target that builds all RPMs for the Cloudera Distribution for Hadoop.
# It generates an RPM with dependencies on all shipped RPMs for a single-source download.
distribution = PackageTarget(
  package_name = "cloudera_distribution",
  version = ":version",
  steps = [
    # Build the "distribution" RPM with /etc/cloudera-version and deps.
    RpmBuild(
      spec_file   ="distribution.spec",
      rpm_build_cmd="-bb --target noarch",
      rpm_release =rpm_release),

    # Mark the git version for the RPM releases
    Exec(
      executable="%(srcdir)/rpm/rpm_build_info",
      arguments =[
        "${rpmdir}",
        rpm_release ])
  ],

  # Build all dependency RPMs
  required_targets = [
    ":supportedHadoopPackage",
    ":pig_rpm",
    ":hive_rpm",
    "//projects/mrunit:package",
  ])

version = VerStringTarget(
  version      = base_ch_ver,
  python_module = "installer.version")

# NOTE(aaron): This is not currently enabled in any way in our distribution.
# include the portal source code
# portalStep = CopyDir(
#  src_dir  = "portal/src",
#  dest_dir = "$/src/webapps/portal")

supportedHadoopPackage = PackageTarget(
  package_name   = "distrib-hadoop",
  steps    = [
    # Relocate the topdir into the assembly dir
    CopyDir(
      src_dir = "rpm/topdir",
      dest_dir = "$/topdir"),

    # Run the rpm build script
    Exec(
      executable="%(srcdir)/rpm/create_rpms",
      arguments=[
        "hadoop",
        "$/buildroot",
        "$/topdir",
        rpm_release,
        base_hadoop_ver ],
      dir="$/topdir"),

    # Create hadoop tarball.
    Tar(
      filename= hadoop_ver_string + ".tar.gz",
      subdir="topdir/BUILD/" + hadoop_ver_string + "/build/" + hadoop_ver_string),

    # Copy output RPMs / SRPMs to toplevel rpm dir
    CopyDir(
      src_dir ="$/topdir/RPMS/",
      dest_dir="${rpmdir}/RPMS/"),
    CopyDir(
      src_dir ="$/topdir/SRPMS/",
      dest_dir="${rpmdir}/SRPMS/"),
  ],

  # Define build-phase outputs that other programs compiled against our distro need.
  outputs = [
      "$/topdir/BUILD/" + hadoop_ver_string + "/build/" + hadoop_ver_string + "-core.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/build/" + hadoop_ver_string + "-test.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/build/" + hadoop_ver_string + "-tools.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/build/" + hadoop_ver_string + "-examples.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/commons-cli-2.0-SNAPSHOT.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/commons-codec-1.3.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/commons-httpclient-3.0.1.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/commons-logging-1.0.4.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/commons-logging-api-1.0.4.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/commons-net-1.4.1.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/jets3t-0.6.0.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/jetty-5.1.4.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/junit-3.8.1.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/kfs-0.1.3.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/log4j-1.2.15.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/oro-2.0.8.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/servlet-api.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/slf4j-api-1.4.3.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/slf4j-log4j12-1.4.3.jar",
      "$/topdir/BUILD/" + hadoop_ver_string + "/lib/xmlenc-0.52.jar",
    ])

# steps for packaging

# the installation system
# NOTE(aaron): This is disabled for now
#installerStep = IncludePackage(
#  target_name = "installer:release",
#  include_zip = False, # we need this unpackacked
#  dest_dir    = "$/bin")

# the log mover system
# NOTE(aaron): This is disabled for now
#logMoverStep = IncludePackage(
#  target_name = "log_mover:release",
#  include_zip = False, # we need this unpackacked
#  dest_dir    = "$/bin/logmover")

pig_rpm = PackageTarget(
  package_name   = "pig-rpm",
  steps    = [
    # Relocate the topdir into the assembly dir
    CopyDir(
      src_dir = "rpm/topdir",
      dest_dir = "$/topdir"),

    # Run the rpm build script
    Exec(
      executable="%(srcdir)/rpm/create_rpms",
      arguments=[
        "pig",
        "%(assemblydir)/buildroot",
        "%(assemblydir)/topdir",
        rpm_release,
        base_hadoop_ver ], # NOTE(aaron): This is the hadoop version; not the pig ver. (hardcoded)
      dir="%(assemblydir)/topdir"),

    # Copy output RPMs / SRPMs to toplevel rpm dir
    CopyDir(
      src_dir ="$/topdir/RPMS/",
      dest_dir="${rpmdir}/RPMS/"),
    CopyDir(
      src_dir ="$/topdir/SRPMS/",
      dest_dir="${rpmdir}/SRPMS/"),
  ])

hive_rpm = PackageTarget(
  package_name   = "hive-rpm",
  steps    = [
    # Relocate the topdir into the assembly dir
    CopyDir(
      src_dir = "rpm/topdir",
      dest_dir = "$/topdir"),

    # Run the rpm build script
    Exec(
      executable="%(srcdir)/rpm/create_rpms",
      arguments=[
        "hive",
        "%(assemblydir)/buildroot",
        "%(assemblydir)/topdir",
        rpm_release,
        base_hadoop_ver ], # NOTE(aaron): This is the hadoop version; not the hive ver. (hardcoded)
      dir="%(assemblydir)/topdir"),

    # Copy output RPMs / SRPMs to toplevel rpm dir
    CopyDir(
      src_dir ="$/topdir/RPMS/",
      dest_dir="${rpmdir}/RPMS/"),
    CopyDir(
      src_dir ="$/topdir/SRPMS/",
      dest_dir="${rpmdir}/SRPMS/"),
  ])


# NOTE(aaron): Contents of doc and deps directories are not currently used/built


# Version stamps: make a single indirection point where all the
# version stamps are listed, so that the installer and test programs
# can depend on only a single place. We only need to update the current
# package version numbers in this single Targets file.
versionStamps = EmptyTarget(
  required_targets = [
    "//thirdparty/hive-chd-0.3.0:version",
    "//thirdparty/pig-0.1.1:version",
    ":version" ])

# subdirectory targets:
#   installer -- guided and noattend python installation system
#   test      -- Cluster Test tool (not included in distro itself)
ProjectList(required_targets=[
  "installer",
  "log_mover",
  "test"
  ])


defaultTarget(distribution)

