#!/bin/sh

bin=`dirname $0`
bin=`cd ${bin} && pwd`

# the 'prefix' below will be replaced by a sed script run by cloudera/install_hadoop.sh
SQOOP_JAR_PATH="SQOOP_PREFIX/contrib/sqoop"

SQOOP_JAR=`ls -1 ${SQOOP_JAR_PATH}/hadoop-*-sqoop.jar | head -n 1`
${bin}/hadoop jar ${SQOOP_JAR} org.apache.hadoop.sqoop.Sqoop "$@"

