CREATE TABLE invites (foo INT, bar STRING) PARTITIONED BY (ds STRING);
LOAD DATA LOCAL INPATH './invites1.txt' OVERWRITE INTO TABLE invites
  PARTITION (ds='2008-08-15');
LOAD DATA LOCAL INPATH './invites2.txt' OVERWRITE INTO TABLE invites
  PARTITION (ds='2008-08-08');
