#!/usr/bin/env bash

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -x
set -e

cd $(dirname $0)

H=$HADOOP_HOME/bin/hadoop

cat > myfile << EOF
here is a sample
file

that is going to be put
into HDFS
EOF

$H fs -put myfile myfile
TMPFILE=`mktemp /tmp/circus-XXXXXX`
$H fs -cat myfile > $TMPFILE
diff $TMPFILE myfile
$H fsck /
$H fs -mkdir foo
$H fs -mv myfile foo/myfile
$H fsck /
$H fs -rmr foo
$H fsck /
rm myfile
