# (c) Copyright 2008 Cloudera, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# module: com.cloudera.distribution.hadoopconf
#
# Writes out properties in Hadoop XML Configuration format
# e.g., hadoop-site.xml



import time

from com.cloudera.distribution.constants import *


def writePropertiesBody(handle, dict, finalKeys):
  """ Given a handle to a file opened in write mode, write the body
      of the properties file out by dumping in the entire contents of
      'dict'. Any keys in 'dict' that are in the finalKeys list are
      marked as final. """

  def writeHadoopSiteKey(handle, key):
    try:
      finalKeys.index(key)
      # it's in the list of 'final' things. Mark is that way.
      finalStr = "\n  <final>true</final>"
    except ValueError:
      # not a final value, just a default.
      finalStr = ""

    outVal = dict[key]
    if outVal == True:
      outVal = "true"
    elif outVal == False:
      outVal = "false"
    else:
      outVal = str(outVal)

    handle.write("""<property>
  <name>%(name)s</name>
  <value>%(val)s</value>%(final)s
</property>
""" % {   "name"  : key,
          "val"   : outVal,
          "final" : finalStr })


  # Write out everything the user configured for us.
  keys = dict.keys()
  keys.sort()
  for key in keys:
    writeHadoopSiteKey(handle, key)


def writePropertiesFooter(handle):
  """ Write out the closing lines of the properties file """

  # This must be the last line in the file.
  handle.write("</configuration>\n")


def writePropertiesHeader(handle):
  """ Write out the opening lines of the properties file """

  dateStr = time.asctime()
  handle.write("""<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<!--
     Autogenerated by Cloudera Hadoop Installer %(ver)s on
     %(thedate)s

     You *may* edit this file. Put site-specific property overrides below.
-->
<configuration>
""" % { "ver"     : DISTRIB_VERSION,
        "thedate" : dateStr })



