#!/usr/bin/env bash

set -x
set -e

cd $HADOOP_HOME

HADOOP=$(basename $HADOOP_HOME)

FILES=(
  cloudera/CHANGES.cloudera.txt
#  docs/jdiff-cloudera/changes.html
  lib/native/Linux-i386-32/libhadoop.so.1.0.0
  lib/native/Linux-i386-32/libhadoop.so
  lib/native/Linux-i386-32/libhadoop.so.1
  lib/native/Linux-i386-32/libhadoop.a
  lib/native/Linux-i386-32/libhadoop.la
  lib/native/Linux-amd64-64/libhadoop.so.1.0.0
  lib/native/Linux-amd64-64/libhadoop.so
  lib/native/Linux-amd64-64/libhadoop.so.1
  lib/native/Linux-amd64-64/libhadoop.a
  lib/native/Linux-amd64-64/libhadoop.la
  lib/$HADOOP-fairscheduler.jar
  docs/index.html
  c++/Linux-amd64-64/lib/libhadooputils.a
  c++/Linux-amd64-64/lib/libhdfs.so
  c++/Linux-amd64-64/lib/libhadooppipes.a
  c++/Linux-amd64-64/lib/libhdfs.so.0
  c++/Linux-amd64-64/lib/libhdfs.la
  c++/Linux-amd64-64/lib/libhdfs.so.0.0.0
  c++/Linux-i386-32/lib/libhadooputils.a
  c++/Linux-i386-32/lib/libhdfs.so
  c++/Linux-i386-32/lib/libhadooppipes.a
  c++/Linux-i386-32/lib/libhdfs.so.0
  c++/Linux-i386-32/lib/libhdfs.la
  c++/Linux-i386-32/lib/libhdfs.so.0.0.0
  example-confs/conf.pseudo/README
  bin/sqoop
  lib/$HADOOP-scribe-log4j.jar
  lib/libthrift.jar
  lib/libfb303.jar
)

for file in ${FILES[*]} ; do
  echo Checking for $file...
  test -e $file
done

./bin/hadoop version | (
  read hadoop version
  if [ $version != ${HADOOP#hadoop-} ]; then
    echo Version $version doesnt match $HADOOP
    exit 1
  fi

  read x x githash
  if ! [[ $githash =~ [a-z0-9]{40} ]]; then
    echo Bad git hash: $githash
    exit 1
  fi
)
