#!/bin/bash -x
# Creates the cloudera/ dir inside of a package.
# This dir initially contains the "redistributable tools" tools/redist
# and the set of git patches between the given base branch and build branch
# from a git repo
set -e
TOOLS_DIR=$(readlink -f $(dirname $0))

GIT_REPO=$1
BASE_BRANCH=$2
BUILD_BRANCH=$3
TARGET_DIR=$4
VERSION=$5
PKG_NAME=$6
PKG_VERSION=$7
PKG_RELEASE=$8
CDH_REL=$9
COMPONENT_HASH=${10}
PACKAGING_HASH=${11}
CDH_HASH=${12}
SRC_PREFIX=${13}

CLOUDERA_DIR=$TARGET_DIR
rm -Rf $CLOUDERA_DIR
mkdir -p $CLOUDERA_DIR

# Format patches into cloudera dir
mkdir -p $CLOUDERA_DIR/patches
$TOOLS_DIR/export_patchseries $GIT_REPO $BASE_BRANCH $BUILD_BRANCH $CLOUDERA_DIR/patches $SRC_PREFIX

# Generate cloudera change log
(cd $GIT_REPO && git log $BASE_BRANCH..$BUILD_BRANCH) > $CLOUDERA_DIR/CHANGES.cloudera.txt

# Copy redistributed tools
for tool in $TOOLS_DIR/redist/* ; do
  cp -a $tool $CLOUDERA_DIR/
done

# Setup build.properties file for ant
$TOOLS_DIR/generate-build-properties $GIT_REPO $BASE_BRANCH $BUILD_BRANCH $CLOUDERA_DIR/build.properties $VERSION $PKG_VERSION $PKG_RELEASE $PKG_NAME $CDH_REL ${COMPONENT_HASH} ${PACKAGING_HASH} ${CDH_HASH}
