#!/bin/bash

set -e

start_dir=$1
oldcdh=$2
newcdh=$3
oldpom=$4
newpom=$5

lower_version="$(echo ${oldcdh}| tr [A-Z] [a-z])"

# Change versions!

for dir in $start_dir/*
do
    cd $dir
    find $start_dir -name "*pom.xml" -exec grep -H "\-${oldcdh}-SNAPSHOT" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/\-${oldcdh}-SNAPSHOT/\-${oldcdh}/g" {}
    find $start_dir -name "*pom.xml" -exec grep -H "${oldpom}-SNAPSHOT" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/${oldpom}-SNAPSHOT/${oldpom}/g" {}

    if [ "${dir}" = "${start_dir}/oozie" ]; then
        find $dir/cloudera -name "do-release-build" -exec grep -H "\-${oldcdh}-SNAPSHOT" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/\-${oldcdh}-SNAPSHOT/\-${oldcdh}/g" {}
    fi

    if [ "${dir}" = "${start_dir}/hive" ]; then
        find $dir/cloudera -name "hive-site.xml" -exec grep -H "\-${oldcdh}-SNAPSHOT" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/\-${oldcdh}-SNAPSHOT/\-${oldcdh}/g" {}
    fi

    
    OLD_BRANCH=$(git symbolic-ref --quiet HEAD|sed 's/refs\/heads\///')
    TAG=${OLD_BRANCH}-${lower_version}-tag
    NEW_BRANCH=${OLD_BRANCH}-${lower_version}-release
    (git ls-files -m | xargs git add && git commit -m "CLOUDERA-BUILD. Preparing for ${oldcdh} release.")
    git tag -m "CLOUDERA-BUILD. Tagging for CDH3B4 release." ${TAG}
    git branch ${NEW_BRANCH}

    find $start_dir -name "*pom.xml" -exec grep -H "\-${oldcdh}" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/\-${oldcdh}/\-${newcdh}-SNAPSHOT/g" {}
    find $start_dir -name "*pom.xml" -exec grep -H "${oldpom}" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/${oldpom}/${newpom}-SNAPSHOT/g" {}

    if [ "${dir}" = "${start_dir}/oozie" ]; then
        find $dir/cloudera -name "do-release-build" -exec grep -H "\-${oldcdh}" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/\-${oldcdh}/\-${newcdh}-SNAPSHOT/g" {}
    fi

    if [ "${dir}" = "${start_dir}/hive" ]; then
        find $dir/cloudera -name "hive-site.xml" -exec grep -H "\-${oldcdh}" {} \;|cut -f1 -d' '| sed 's/\://'|xargs -I {} perl -p -i -e "s/\-${oldcdh}/\-${newcdh}-SNAPSHOT/g" {}
    fi

    (git ls-files -m | xargs git add && git commit -m "CLOUDERA-BUILD. Preparing for ${newcdh} development.")
#    git push origin $OLD_BRANCH
#    git push origin $TAG
#    git push origin $NEW_BRANCH
done

perl -p -i -e "s/\-${oldcdh}-SNAPSHOT/\-${newcdh}-SNAPSHOT/g" pom.xml
perl -p -i -e "s/${oldpom}-SNAPSHOT/${newpom}-SNAPSHOT/g" pom.xml
perl -p -i -e "s/\-${oldcdh}-SNAPSHOT/\-${newcdh}-SNAPSHOT/g" package.mk

git add pom.xml package.mk
git commit -m "CLOUDERA-BUILD. Switching versions for ${newcdh} development."
#git push origin master
