#!/usr/bin/python
#
# (c) Copyright 2009 Cloudera, Inc.
#

logMover = PythonTarget(
  sources=[ "src/common.py",
            "src/db",
            "src/log_to_db.py",
            "src/log_to_dbs",
            "src/persist.py",
            "src/persisters",
            "src/prune.py",
            "src/pruners",
            "src/settings.py",
            "src/db_init.sql",
            "src/db_user_and_db.sql"],
  required_targets = [ "//python/Common" ])

# packaging the log mover up for use in the tarball
release = PythonRedistTarget(
  package_name     = "log_mover",
  required_targets = [ ":logMover" ])

