#!/usr/bin/env bash

set -x
set -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd $(dirname $0)
pwd

CORE_JAR=$(find $HADOOP_HOME | grep core.jar)
export CLASSPATH=$CORE_JAR
echo $CLASSPATH

H=$HADOOP_HOME/bin/hadoop

mkdir -p wordcount_classes
javac -d wordcount_classes WordCount.java
jar -cvf wordcount.jar -C wordcount_classes/ .

if ! $H fs -rmr output
then
  echo "no output file; ignoring"
fi

if ! $H fs -rmr input
then
  echo "no input file; ignoring"
fi
$H fs -mkdir input
$H fs -put input input/

$H jar wordcount.jar WordCount input output

TMPFILE=`mktemp /tmp/circus-XXXXXX`
$H fs -cat output/part-00000 > $TMPFILE
diff expected_output $TMPFILE

rm -R wordcount_classes
rm wordcount.jar
