#!/usr/bin/python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Installation system for Cloudera Hadoop
#



installer = PythonTarget(
  sources=[ "src/install",
            "src/com"],
  requiredTargets=[ "python/Common" ])


# packaging the installer up for use in the tarball
release = PythonRedistTarget(
  distribName     = "installer",
  requiredTargets = [ ":installer" ])

