#!/usr/bin/python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Installation system for Cloudera Hadoop
#

installer = PythonTarget(
  sources=[ "src/install",
            "src/installer",
            "src/com"],
  required_targets=[ "//python/Common",
                    "..:versionStamps" ])

installerTest = PythonTestTarget(
  sources = ["test/com/"],
  main_module = "com.cloudera.distribution.alltests",
  required_targets = [":installer",
                     "//python/Common"])

# packaging the installer up for use in the tarball
release = PythonRedistTarget(
  package_name     = "installer",
  required_targets = [ ":installer" ])

defaultTarget(release)
