#!/usr/bin/python
#
# (c) Copyright 2008 Cloudera, Inc.
#
# Installation system for Cloudera Hadoop
#

installerVersion = VerStringTarget(
  version     ="0.2.0",
  pythonModule="installer.version")

installer = PythonTarget(
  sources=[ "src/install",
            "src/com"],
  requiredTargets=[ "python/Common",
                    ":installerVersion" ])

installerTest = PythonTestTarget(
  sources = ["test/com/"],
  mainModule = "com.cloudera.distribution.alltests",
  requiredTargets = [":installer",
                     "python/Common"])

# packaging the installer up for use in the tarball
release = PythonRedistTarget(
  distribName     = "installer",
  requiredTargets = [ ":installer" ])

defaultTarget(release)
